package com.stone.etour.mapper;

import com.stone.etour.bean.EtourUser;
import com.stone.etour.bean.EtourUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtourUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int countByExample(EtourUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int deleteByExample(EtourUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int insert(EtourUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int insertSelective(EtourUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    List<EtourUser> selectByExample(EtourUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    EtourUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") EtourUser record, @Param("example") EtourUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int updateByExample(@Param("record") EtourUser record, @Param("example") EtourUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int updateByPrimaryKeySelective(EtourUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_user
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    int updateByPrimaryKey(EtourUser record);
}