package com.stone.etour.bean;

public class EtourUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.id
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.name
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.password
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.email
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.phone
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.save_path
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private String savePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_user.level
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.id
     *
     * @return the value of etour_user.id
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.id
     *
     * @param id the value for etour_user.id
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.name
     *
     * @return the value of etour_user.name
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.name
     *
     * @param name the value for etour_user.name
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.password
     *
     * @return the value of etour_user.password
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.password
     *
     * @param password the value for etour_user.password
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.email
     *
     * @return the value of etour_user.email
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.email
     *
     * @param email the value for etour_user.email
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.phone
     *
     * @return the value of etour_user.phone
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.phone
     *
     * @param phone the value for etour_user.phone
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.save_path
     *
     * @return the value of etour_user.save_path
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public String getSavePath() {
        return savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.save_path
     *
     * @param savePath the value for etour_user.save_path
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setSavePath(String savePath) {
        this.savePath = savePath == null ? null : savePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_user.level
     *
     * @return the value of etour_user.level
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_user.level
     *
     * @param level the value for etour_user.level
     *
     * @mbggenerated Tue Dec 17 16:54:12 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}