package com.stone.etour.bean;

import java.util.ArrayList;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOIdIsNull() {
            addCriterion("o_id is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("o_id is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Integer value) {
            addCriterion("o_id =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Integer value) {
            addCriterion("o_id <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Integer value) {
            addCriterion("o_id >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_id >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Integer value) {
            addCriterion("o_id <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Integer value) {
            addCriterion("o_id <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Integer> values) {
            addCriterion("o_id in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Integer> values) {
            addCriterion("o_id not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Integer value1, Integer value2) {
            addCriterion("o_id between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Integer value1, Integer value2) {
            addCriterion("o_id not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andONameIsNull() {
            addCriterion("o_name is null");
            return (Criteria) this;
        }

        public Criteria andONameIsNotNull() {
            addCriterion("o_name is not null");
            return (Criteria) this;
        }

        public Criteria andONameEqualTo(String value) {
            addCriterion("o_name =", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameNotEqualTo(String value) {
            addCriterion("o_name <>", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameGreaterThan(String value) {
            addCriterion("o_name >", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameGreaterThanOrEqualTo(String value) {
            addCriterion("o_name >=", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameLessThan(String value) {
            addCriterion("o_name <", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameLessThanOrEqualTo(String value) {
            addCriterion("o_name <=", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameLike(String value) {
            addCriterion("o_name like", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameNotLike(String value) {
            addCriterion("o_name not like", value, "oName");
            return (Criteria) this;
        }

        public Criteria andONameIn(List<String> values) {
            addCriterion("o_name in", values, "oName");
            return (Criteria) this;
        }

        public Criteria andONameNotIn(List<String> values) {
            addCriterion("o_name not in", values, "oName");
            return (Criteria) this;
        }

        public Criteria andONameBetween(String value1, String value2) {
            addCriterion("o_name between", value1, value2, "oName");
            return (Criteria) this;
        }

        public Criteria andONameNotBetween(String value1, String value2) {
            addCriterion("o_name not between", value1, value2, "oName");
            return (Criteria) this;
        }

        public Criteria andOUserIsNull() {
            addCriterion("o_user is null");
            return (Criteria) this;
        }

        public Criteria andOUserIsNotNull() {
            addCriterion("o_user is not null");
            return (Criteria) this;
        }

        public Criteria andOUserEqualTo(String value) {
            addCriterion("o_user =", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserNotEqualTo(String value) {
            addCriterion("o_user <>", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserGreaterThan(String value) {
            addCriterion("o_user >", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserGreaterThanOrEqualTo(String value) {
            addCriterion("o_user >=", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserLessThan(String value) {
            addCriterion("o_user <", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserLessThanOrEqualTo(String value) {
            addCriterion("o_user <=", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserLike(String value) {
            addCriterion("o_user like", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserNotLike(String value) {
            addCriterion("o_user not like", value, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserIn(List<String> values) {
            addCriterion("o_user in", values, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserNotIn(List<String> values) {
            addCriterion("o_user not in", values, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserBetween(String value1, String value2) {
            addCriterion("o_user between", value1, value2, "oUser");
            return (Criteria) this;
        }

        public Criteria andOUserNotBetween(String value1, String value2) {
            addCriterion("o_user not between", value1, value2, "oUser");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesIsNull() {
            addCriterion("o_simple_des is null");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesIsNotNull() {
            addCriterion("o_simple_des is not null");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesEqualTo(String value) {
            addCriterion("o_simple_des =", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesNotEqualTo(String value) {
            addCriterion("o_simple_des <>", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesGreaterThan(String value) {
            addCriterion("o_simple_des >", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesGreaterThanOrEqualTo(String value) {
            addCriterion("o_simple_des >=", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesLessThan(String value) {
            addCriterion("o_simple_des <", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesLessThanOrEqualTo(String value) {
            addCriterion("o_simple_des <=", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesLike(String value) {
            addCriterion("o_simple_des like", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesNotLike(String value) {
            addCriterion("o_simple_des not like", value, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesIn(List<String> values) {
            addCriterion("o_simple_des in", values, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesNotIn(List<String> values) {
            addCriterion("o_simple_des not in", values, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesBetween(String value1, String value2) {
            addCriterion("o_simple_des between", value1, value2, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOSimpleDesNotBetween(String value1, String value2) {
            addCriterion("o_simple_des not between", value1, value2, "oSimpleDes");
            return (Criteria) this;
        }

        public Criteria andOPriceIsNull() {
            addCriterion("o_price is null");
            return (Criteria) this;
        }

        public Criteria andOPriceIsNotNull() {
            addCriterion("o_price is not null");
            return (Criteria) this;
        }

        public Criteria andOPriceEqualTo(Double value) {
            addCriterion("o_price =", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotEqualTo(Double value) {
            addCriterion("o_price <>", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceGreaterThan(Double value) {
            addCriterion("o_price >", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("o_price >=", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLessThan(Double value) {
            addCriterion("o_price <", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceLessThanOrEqualTo(Double value) {
            addCriterion("o_price <=", value, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceIn(List<Double> values) {
            addCriterion("o_price in", values, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotIn(List<Double> values) {
            addCriterion("o_price not in", values, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceBetween(Double value1, Double value2) {
            addCriterion("o_price between", value1, value2, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOPriceNotBetween(Double value1, Double value2) {
            addCriterion("o_price not between", value1, value2, "oPrice");
            return (Criteria) this;
        }

        public Criteria andOTimeIsNull() {
            addCriterion("o_time is null");
            return (Criteria) this;
        }

        public Criteria andOTimeIsNotNull() {
            addCriterion("o_time is not null");
            return (Criteria) this;
        }

        public Criteria andOTimeEqualTo(String value) {
            addCriterion("o_time =", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeNotEqualTo(String value) {
            addCriterion("o_time <>", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeGreaterThan(String value) {
            addCriterion("o_time >", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeGreaterThanOrEqualTo(String value) {
            addCriterion("o_time >=", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeLessThan(String value) {
            addCriterion("o_time <", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeLessThanOrEqualTo(String value) {
            addCriterion("o_time <=", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeLike(String value) {
            addCriterion("o_time like", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeNotLike(String value) {
            addCriterion("o_time not like", value, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeIn(List<String> values) {
            addCriterion("o_time in", values, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeNotIn(List<String> values) {
            addCriterion("o_time not in", values, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeBetween(String value1, String value2) {
            addCriterion("o_time between", value1, value2, "oTime");
            return (Criteria) this;
        }

        public Criteria andOTimeNotBetween(String value1, String value2) {
            addCriterion("o_time not between", value1, value2, "oTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table etour_order
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 24 23:02:26 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table etour_order
     *
     * @mbggenerated Sun Nov 24 23:02:26 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}