package com.stone.etour.bean;

public class Tour {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.id
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.tour_num
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private String tourNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.name
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.type
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.price
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.simple_des
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private String simpleDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.description
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.status
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.people_num
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private Integer peopleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.total
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column etour_tour.save_path
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    private String savePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.id
     *
     * @return the value of etour_tour.id
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.id
     *
     * @param id the value for etour_tour.id
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.tour_num
     *
     * @return the value of etour_tour.tour_num
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public String getTourNum() {
        return tourNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.tour_num
     *
     * @param tourNum the value for etour_tour.tour_num
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setTourNum(String tourNum) {
        this.tourNum = tourNum == null ? null : tourNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.name
     *
     * @return the value of etour_tour.name
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.name
     *
     * @param name the value for etour_tour.name
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.type
     *
     * @return the value of etour_tour.type
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.type
     *
     * @param type the value for etour_tour.type
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.price
     *
     * @return the value of etour_tour.price
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.price
     *
     * @param price the value for etour_tour.price
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.simple_des
     *
     * @return the value of etour_tour.simple_des
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public String getSimpleDes() {
        return simpleDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.simple_des
     *
     * @param simpleDes the value for etour_tour.simple_des
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setSimpleDes(String simpleDes) {
        this.simpleDes = simpleDes == null ? null : simpleDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.description
     *
     * @return the value of etour_tour.description
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.description
     *
     * @param description the value for etour_tour.description
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.status
     *
     * @return the value of etour_tour.status
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.status
     *
     * @param status the value for etour_tour.status
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.people_num
     *
     * @return the value of etour_tour.people_num
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public Integer getPeopleNum() {
        return peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.people_num
     *
     * @param peopleNum the value for etour_tour.people_num
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setPeopleNum(Integer peopleNum) {
        this.peopleNum = peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.total
     *
     * @return the value of etour_tour.total
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.total
     *
     * @param total the value for etour_tour.total
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column etour_tour.save_path
     *
     * @return the value of etour_tour.save_path
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public String getSavePath() {
        return savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column etour_tour.save_path
     *
     * @param savePath the value for etour_tour.save_path
     *
     * @mbggenerated Sun Nov 24 23:57:54 CST 2019
     */
    public void setSavePath(String savePath) {
        this.savePath = savePath == null ? null : savePath.trim();
    }
}